apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-shell
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/biswajitind/infra.git
    targetRevision: main
    path: tools/argo-shell
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
