apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
spec:
  project: default

  sources:
    # Source 1: Helm chart pinned to chart version
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 6.7.12
      helm:
        valueFiles:
          - $values/core/argocd/values.yaml

    # Source 2: Your private repo holding values.yaml
    - repoURL: https://github.com/biswajitind/infra.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
