apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamlit-mysql.fullname" . }}-mysql
  labels:
    {{- include "streamlit-mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mysql
