apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubernetes-retired/dashboard.git
      targetRevision: kubernetes-dashboard-7.14.0
      path: charts/kubernetes-dashboard
      helm:
        valueFiles:
          - $values/kube-dash/values.yaml

    - repoURL: https://github.com/biswajitind/infra.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-dashboard

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
